name: apiverve_bingocardgenerator
description: Bingo Card Generator creates customizable bingo cards with random numbers, HTML rendering, and downloadable PNG images.
version: 1.1.13
homepage: https://apiverve.com/marketplace/bingocardgenerator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/bingocardgenerator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
